#!/usr/bin/env python3
"""Derive the three exact reduced ideals for Proposition 4.3 case (2).

Input is the characteristic-zero lexicographic top-edge basis generated by
``model_linear_edge.py`` and Singular. All subsequent elimination is exact.
The output coefficient field is Q(theta), where theta=a1^7 and the degree-five
minimal polynomial is read from the basis itself.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
import sympy as sp
from sympy.polys.domains import QQ
from sympy.polys.rings import ring

ROOT = Path(__file__).resolve().parent


def parse_top_edge(path: Path):
    text = path.read_text()
    lines = {int(i): e for i, e in re.findall(r"L\[(\d+)\]=(.*)", text)}
    if set(lines) != set(range(1, 18)):
        raise RuntimeError(f"expected L[1]..L[17], got {sorted(lines)}")
    t, q = sp.symbols("t q")
    p_t = sp.Poly(sp.sympify(lines[1].replace("^", "**"), locals={"a1": t}), t, domain=sp.QQ)
    p_q = sp.Poly(sum(p_t.coeff_monomial(t ** (7 * j)) * q**j for j in range(6)), q, domain=sp.QQ)
    if p_q.degree() != 5 or not p_q.is_irreducible:
        raise RuntimeError("top-edge quotient polynomial is not irreducible of degree five")
    K = QQ.alg_field_from_poly(p_q, alias="theta")
    theta = K.new([QQ.one, QQ.zero])

    def qpoly_to_K(expr):
        pp = sp.Poly(expr, q, domain=sp.QQ)
        return K.new([QQ.convert(c) for c in pp.all_coeffs()])

    def laurent_to_K(terms):
        lo = min(terms) if terms else 0
        shift = max(0, -lo)
        ans = qpoly_to_K(sum(sp.Rational(c) * q ** (j + shift) for j, c in terms.items()))
        return ans * theta ** (-shift)

    def scaled_solution(line, variable, weight):
        names = [f"a{i}" for i in range(2, 7)] + [f"d{i}" for i in range(1, 11)] + ["z"]
        loc = {name: sp.symbols(name) for name in names}
        loc["a1"] = t
        expr = sp.expand(sp.sympify(line.replace("^", "**"), locals=loc))
        var = loc[variable]
        coefficient = sp.Rational(expr.coeff(var))
        solution = sp.Poly(-(expr - coefficient * var) / coefficient, t, domain=sp.QQ)
        terms = {}
        for (exponent,), coeff in solution.terms():
            if (exponent - weight) % 7:
                raise RuntimeError((variable, exponent, weight))
            terms[(exponent - weight) // 7] = coeff
        return laurent_to_K(terms)

    C = [K.one] * 8
    G = [K.one] * 11
    C[1] = K.one
    for i in range(2, 7):
        C[i] = scaled_solution(lines[i], f"a{i}", i)
    C[7] = theta ** -1
    for j in range(1, 11):
        G[j] = scaled_solution(lines[6 + j], f"d{j}", j)

    for n in range(18):
        value = K.zero
        for i in range(8):
            j = n - i
            if 0 <= j < 11:
                value += K.convert(1 + 2 * j - 3 * i) * C[i] * G[j]
        expected = K.one if n == 0 else K.zero
        if value != expected:
            raise RuntimeError(("top edge replay", n, value))
    return K, theta, p_q, C, G


def rref(K, matrix, rhs=None):
    A = [row[:] for row in matrix]
    b = None if rhs is None else rhs[:]
    rows, cols = len(A), len(A[0])
    pivots = []
    r = 0
    for col in range(cols):
        pivot = next((i for i in range(r, rows) if A[i][col] != K.zero), None)
        if pivot is None:
            continue
        A[r], A[pivot] = A[pivot], A[r]
        if b is not None:
            b[r], b[pivot] = b[pivot], b[r]
        inverse = A[r][col] ** -1
        A[r] = [x * inverse for x in A[r]]
        if b is not None:
            b[r] = b[r] * inverse
        for i in range(rows):
            if i != r and A[i][col] != K.zero:
                factor = A[i][col]
                A[i] = [A[i][j] - factor * A[r][j] for j in range(cols)]
                if b is not None:
                    b[i] = b[i] - factor * b[r]
        pivots.append(col)
        r += 1
        if r == rows:
            break
    return A, b, pivots


def nullspace(K, matrix):
    reduced, _, pivots = rref(K, matrix)
    free = [j for j in range(len(matrix[0])) if j not in pivots]
    result = []
    for free_col in free:
        vector = [K.zero] * len(matrix[0])
        vector[free_col] = K.one
        for i, pivot in enumerate(pivots):
            vector[pivot] = -reduced[i][free_col]
        result.append(vector)
    return result, pivots


def derive(path: Path):
    K, theta, minpoly, C, G = parse_top_edge(path)

    M3 = []
    for n in range(18):
        row = []
        for i in range(8):
            j = n - i
            row.append(K.convert(j - 3 * i - 1) * G[j] if 0 <= j < 11 else K.zero)
        for j in range(11):
            i = n - j
            row.append(K.convert(2 * (1 + j - i)) * C[i] if 0 <= i < 8 else K.zero)
        M3.append(row)
    N3, pivots3 = nullspace(K, M3)
    if len(N3) != 2:
        raise RuntimeError(("W3 nullity", len(N3)))

    S, p, q, h, k = ring("p,q,h,k", K)
    ground = S.ground_new
    B = [ground(N3[0][i]) * p + ground(N3[1][i]) * q for i in range(8)]
    F = [ground(N3[0][8 + j]) * p + ground(N3[1][8 + j]) * q for j in range(11)]

    M2, rhs2 = [], []
    for n in range(19):
        row = []
        for ai in range(1, 9):
            j = n - ai
            row.append(K.convert(-3 * ai) * G[j] if 0 <= j < 11 else K.zero)
        for ej in range(12):
            i = n - ej
            row.append(K.convert(1 + 2 * ej - i) * C[i] if 0 <= i < 8 else K.zero)
        nonlinear = S.zero
        if n >= 1:
            for i in range(8):
                j = n - 1 - i
                if 0 <= j < 11:
                    nonlinear += (j - 2 * i) * B[i] * F[j]
        M2.append(row)
        rhs2.append(-nonlinear)
    reduced2, rhs_reduced, pivots2 = rref(K, M2, rhs2)
    free2 = [j for j in range(20) if j not in pivots2]
    if free2 != [18, 19]:
        raise RuntimeError(("W2 free columns", free2))
    for i in range(len(pivots2), 19):
        if any(x != K.zero for x in reduced2[i]) or rhs_reduced[i] != S.zero:
            raise RuntimeError(("W2 consistency", i))
    unknowns = [S.zero] * 20
    for j, parameter in zip(free2, [h, k]):
        unknowns[j] = parameter
    for i, pivot in enumerate(pivots2):
        value = rhs_reduced[i]
        for j, parameter in zip(free2, [h, k]):
            value -= ground(reduced2[i][j]) * parameter
        unknowns[pivot] = value
    A = [S.zero] + unknowns[:8]
    E = unknowns[8:]

    V = [S.zero] * 13
    consistency = []
    for n in range(19):
        expr = S.zero
        for i in range(1, 8):
            j = n + 1 - i
            if 1 <= j <= 12:
                expr += ground(K.convert(2 * j) * C[i]) * V[j]
        for i in range(8):
            j = n - i
            if 0 <= j < 12:
                expr += (j - i) * B[i] * E[j]
            if 0 <= j < 11 and 1 <= i <= 8:
                expr -= 2 * i * A[i] * F[j]
        if n <= 11:
            V[n + 1] = -expr / (2 * (n + 1))
        else:
            consistency.append(expr)

    for n in range(19):
        expr = S.zero
        for i in range(8):
            j = n + 1 - i
            if 1 <= j <= 12:
                expr += j * B[i] * V[j]
        for i in range(1, 9):
            j = n + 1 - i
            if 0 <= j < 12:
                expr -= i * A[i] * E[j]
        consistency.append(expr)
    consistency = [x for x in consistency if x != S.zero]
    if len(consistency) != 25:
        raise RuntimeError(("consistency count", len(consistency)))
    return K, minpoly, S, A, B, V, consistency


def coeff_expr(K, coefficient):
    return K.to_sympy(coefficient)


def ring_expr(K, poly, symbols):
    result = 0
    for monomial, coefficient in poly.terms():
        term = coeff_expr(K, coefficient)
        for symbol, exponent in zip(symbols, monomial):
            term *= symbol**exponent
        result += term
    return sp.expand(result)


def sx(expr):
    return str(sp.expand(expr)).replace("**", "^")


def emit(branch, basis):
    K, minpoly, S, A, B, V, consistency = derive(basis)
    ss, rr = branch
    theta = sp.symbols("theta")
    z, p, q, h, k = sp.symbols("z p q h k")
    symbols = [p, q, h, k]
    equations = [A[i] for i in range(1, rr)] + [B[i] for i in range(ss)] + consistency
    equations = [x for x in equations if x != S.zero]
    product = A[rr] * A[8] * V[12] * B[ss]
    expressions = [ring_expr(K, x, symbols) for x in equations]
    expressions.append(z * ring_expr(K, product, symbols) - 1)
    coefficients = [sp.Rational(c.numerator, c.denominator) for c in K.mod.to_list()]
    phi = sum(c * theta ** (len(coefficients) - 1 - i) for i, c in enumerate(coefficients))
    tag = f"{ss}_{rr}"
    output = ROOT / f"linear_reduced_{tag}_QQ.sing"
    lines = [
        "option(redSB);",
        "ring r=(0,theta),(z,p,q,h,k),dp;",
        f"minpoly={sx(phi)};",
        "ideal I=",
        "  " + ",\n  ".join(sx(e) for e in expressions) + ";",
        f'print("BRANCH {tag} INPUT "+string(size(I)));',
        "matrix T;",
        "ideal G=liftstd(I,T);",
        'print("GB "+string(size(G)));',
        f'if(size(G)==1 && G[1]==1){{print("BRANCH {tag}: UNIT");}}else{{print("BRANCH {tag}: NONUNIT");G;}}',
        "matrix CHECK=matrix(G)-matrix(I)*T;",
        'if(CHECK==0){print("LIFT_CHECK: ZERO");}else{print("LIFT_CHECK: FAILURE");CHECK;}',
        'print("TRANSFORM_ROWS "+string(nrows(T))+" COLS "+string(ncols(T)));',
        "T;",
        "quit;",
    ]
    output.write_text("\n".join(lines) + "\n")
    metadata = {
        "branch": [ss, rr],
        "equations": len(expressions),
        "consistency_equations": len(consistency),
        "top_edge_degree": 5,
        "output": output.name,
    }
    (ROOT / f"linear_reduced_{tag}.json").write_text(json.dumps(metadata, indent=2) + "\n")
    return output


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--basis", type=Path, required=True)
    parser.add_argument("--branch", choices=["1_3", "2_5", "3_7"])
    args = parser.parse_args()
    branches = [tuple(map(int, args.branch.split("_")))] if args.branch else [(1, 3), (2, 5), (3, 7)]
    for branch in branches:
        print(emit(branch, args.basis))


if __name__ == "__main__":
    main()
